// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Core = require("@aws-amplify/core");

function configure(config) {
  Core.default.configure(config);
  return /* () */0;
}

exports.configure = configure;
/* @aws-amplify/core Not a pure module */
