// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Api = require("@aws-amplify/api");

function configure(config) {
  Api.default.configure(config);
  return /* () */0;
}

function mutate(graphqlOperation) {
  return Api.default.graphql(graphqlOperation);
}

exports.configure = configure;
exports.mutate = mutate;
/* @aws-amplify/api Not a pure module */
