// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var AwsExportsJs = require("../aws-exports.js");

var config = AwsExportsJs.default;

exports.config = config;
/* config Not a pure module */
