// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Wonka = require("wonka/src/wonka.js");
var Belt_Option = require("bs-platform/lib/js/belt_Option.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var Api = require("@aws-amplify/api");

function configure(config) {
  Api.default.configure(config);
  return /* () */0;
}

var ClientTypes = { };

function clientResponseToReason(parse, result) {
  var data = Belt_Option.map(result.data, parse);
  var error = result.error;
  var response = data !== undefined ? /* Data */Block.__(0, [Caml_option.valFromOption(data)]) : (
      error !== undefined ? /* Error */Block.__(1, [error]) : /* NotFound */0
    );
  console.log("clientResponseToReason", response);
  return {
          data: data,
          error: error,
          response: response
        };
}

function executeSubscription(request) {
  var req = {
    query: request.query,
    variables: request.variables
  };
  var parse = request.parse;
  return Wonka.map((function (result) {
                  return clientResponseToReason(parse, result);
                }))(Wonka.fromObservable(Api.default.graphql(req)));
}

exports.configure = configure;
exports.ClientTypes = ClientTypes;
exports.clientResponseToReason = clientResponseToReason;
exports.executeSubscription = executeSubscription;
/* Wonka Not a pure module */
