// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pubsub = require("@aws-amplify/pubsub");

function configurePubSub(config) {
  Pubsub.default.configure(config);
  return /* () */0;
}

function subscribe(subscriptionObserver) {
  var partial_arg = Pubsub.default;
  return (function (param) {
      return param.subscribe(partial_arg, subscriptionObserver);
    });
}

exports.configurePubSub = configurePubSub;
exports.subscribe = subscribe;
/* @aws-amplify/pubsub Not a pure module */
