// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var ApiClient$ReactTemplate = require("./ApiClient.bs.js");

var Client = ApiClient$ReactTemplate;

var ApiTypes = /* alias */0;

var $$Request = /* alias */0;

var GraphqlError = /* alias */0;

exports.ApiTypes = ApiTypes;
exports.Client = Client;
exports.$$Request = $$Request;
exports.GraphqlError = GraphqlError;
/* ApiClient-ReactTemplate Not a pure module */
