// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function toJs(error) {
  return {
          message: error.message,
          locations: error.locations,
          path: error.path,
          nodes: error.nodes,
          source: error.source,
          positions: error.positions,
          originalError: error.originalError,
          extensions: error.extensions
        };
}

exports.toJs = toJs;
/* No side effect */
